### ISSUE TITLE
Why were all the source files removed?

### ISSUE THREAD

**Issue by systemsplanet** [lbaird/swirlds-demos#6]
https://github.com/lbaird/swirlds-demos/commit/b8c3373285663ec1f690dd87ee65f29b95bc2331

**Comment by alexgodwin1** [comment]
Hi there, we decided that it was simpler for everyone to download the full SDK from the Swirlds website at https://swirlds.com/download and we also have a much larger developer community on Telegram which can help us answer a much broader set of questions in a shorter amount of time. It would be great if you would join us here if you haven't done so already.

Hashgraph Telegram Community - https://t.me/hashgraph
Hashgraph Developer Community - https://t.me/hashgraphdev

**Comment by systemsplanet** [comment]
Thanks for the offer, but I think I'll pass. Telegram requires a phone number to access the Hashgraph community. That's off-brand for a technology that desires to lead the next wave of distributed decentralized  secure **anonymous** ledgers. 

You need to get paid for your innovation, but using old-school models like closed source and requiring a phone number to participate does not inspire confidence. Good Luck.

**Comment by kakins** [comment]
I somewhat agree with @systemsplanet's comments on Telegram, as I'm not a huge fan of the Telegram medium for participation and communication.

However it's important to note that if he's talking about the 'old school' closed source model in reference to the files that were on GitHub, all of those files are still found in the SDK which can be downloaded and modified.  So they are technically not 'closed source'.

If he's referring to the Swirlds platform itself being closed source, I'd say well, yes they do need to get paid.  They are a company marketing their solutions to large entities.  However, there _is_ a whitepaper on the underlying consensus algorithm, so if you'd like to implement your own platform go right ahead!  Otherwise, I think you're just missing out.

**Comment by freecrm** [comment]
Most dev's use Gitter, Telegram just isn't really a forum that's used often.

**Comment by kakins** [comment]
By the way, there is a Hashgraph gitter channel:
https://gitter.im/hashgraph_twitter

I'm the only one there so far!

**Comment by kylearmour** [comment]
There is also a forum, which better serves devs at https://hashgraphboard.com/
